x-anchors: # CREATE ANCHOR VARIABLES SPECIFIC TO LOCAL ENVIRONMENT
  port: &port 50505
  HOSTIP: &hostip 192.168.37.80
  GPSD_SERVER: &gpsd_server roan
  CONTAINER: &container gpsnet

services:
  gpsnet:
    container_name: *container
    image: &image kd2qar/gpsnet
    environment:
      TZ: Americas/New_York
      PORT: *port
      HOSTIP: *hostip
      GPSD_SERVER: *gpsd_server
      CONTAINER: *container
    build:
      context: .
      args:
        GPSD_SERVER: *gpsd_server
        PORT: *port
        HOSTIP: *hostip
      dockerfile: Dockerfile
      tags:
        - *image
    hostname: *container
    network_mode: bridge
    ports:
      - target: *port
        host_ip: *hostip
        published: *port
        protocol: "tcp"

    #command: /bin/bash
    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
